# Generated by Django 4.0.4 on 2022-05-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='category',
            new_name='category_id',
        ),
    ]
